# Generated by Django 3.2.7 on 2021-09-23 09:29

from django.db import migrations
from ..helpers import parse_dms
import json
from django.contrib.gis.geos import fromstr
import sys

# load nature reserve data from geojson file
def load_data(apps, schema_editor):
    Site = apps.get_model(app_label='sites', model_name='Site')
    jsonfile = r'C:\Users\fangn\PycharmProjects\sunday\data\NNR_cleaned.json'

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects:
            try:
                objType = obj['type']
                if objType == 'Feature':
                    properties = obj['properties']
                    name = properties.get('NNR_NAME','no-name')

                    longitude = properties.get('LONGITUDE', 0)
                    latitude = properties.get('LATITUDE', 0)

                    # convert latlong
                    lat = round(parse_dms(latitude), 6)
                    lon = round(parse_dms(longitude), 6)

                    location = fromstr(f'POINT({lon} {lat})', srid=4326)
                    Site(name=name, location=location).save()
            except KeyError:
                pass

class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_site_name'),
    ]

    # the second argument makes this migration reversible, just in case
    operations = [
        migrations.RunPython(load_data, migrations.RunPython.noop)
    ] if 'test' not in sys.argv[1:] else []
